name: Generate File List

on: workflow_dispatch

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code            # Check out the repository code
        uses: actions/checkout@v4                                  
   
      - name: Set up Python              # Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
     
      - name: Generate file list          # Run the script to generate the file list
        run: |
          mkdir -p output
          python -c "
          import os
          
          # Specify the directory to list files from
          folder_path = 'MusicPlayer/wwwroot/audio'
          output_file = 'output/songs_list.txt'
          
          # Check if the folder exists
          if not os.path.exists(folder_path):
              raise FileNotFoundError(f'The directory {folder_path} does not exist.')
          
          files = os.listdir(folder_path)  # Get a list of files in the folder
          
          # Write the file list to a text file
          with open(output_file, 'w') as f:
              for file in files:
                  f.write(file + '\n')
          "
    
      - name: Upload artifact            # Upload the generated file list as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: file-list
          path: output/songs_list.txt
